# Generated by Django 2.1.3 on 2018-11-24 15:06

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='users',
        ),
        migrations.AddField(
            model_name='game',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='location',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(x=18.66, y=50.29), srid=4326),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='games',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='games',
            field=models.ManyToManyField(related_name='games', to='api.Game'),
        ),
    ]
