# Generated by Django 2.1.3 on 2018-11-24 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181124_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='wonCoupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Coupon'),
        ),
    ]
