# Generated by Django 2.1.3 on 2018-11-24 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181124_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='wonCoupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Coupon'),
        ),
    ]
