# Generated by Django 2.1.3 on 2018-11-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181124_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='locations',
            field=models.ManyToManyField(related_name='locations', to='api.Location'),
        ),
    ]
