# Generated by Django 2.1.3 on 2018-11-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_game_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelocation',
            name='game',
        ),
        migrations.AlterField(
            model_name='game',
            name='locations',
            field=models.ManyToManyField(related_name='locations', to='api.GameLocation'),
        ),
    ]
