# Generated by Django 2.1.3 on 2018-11-24 17:56

import api.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20181124_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamequestion',
            name='status',
            field=models.CharField(choices=[('TO_ANSWER', 'TO_ANSWER'), ('ANSWERED_CORRECTLY', 'ANSWERED_CORRECTLY'), ('ANSWERED_INCORRECTLY', 'ANSWERED_INCORRECTLY')], default=api.enums.GameQuestionStatus('TO_ANSWER'), max_length=20),
        ),
    ]
