# Generated by Django 2.1.3 on 2018-11-25 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20181124_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(verbose_name='date published')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('prize', models.BigIntegerField()),
                ('games', models.ManyToManyField(related_name='lottery_games', to='api.Game')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='won_lotteries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Lottery'),
        ),
    ]
