# Generated by Django 2.1.3 on 2018-11-25 00:22

import api.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20181125_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamequestion',
            name='status',
            field=models.CharField(choices=[('TO_ANSWER', 'TO_ANSWER'), ('ANSWERED_CORRECTLY', 'ANSWERED_CORRECTLY'), ('ANSWERED_INCORRECTLY', 'ANSWERED_INCORRECTLY')], default=api.enums.GameQuestionStatus('TO_ANSWER'), max_length=30),
        ),
    ]
