# Generated by Django 2.1.3 on 2018-11-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20181125_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lottery',
            name='games',
        ),
        migrations.AddField(
            model_name='lottery',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='lottery_games', to='api.Game'),
        ),
    ]
