# Generated by Django 2.1.3 on 2018-11-25 02:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20181125_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='tier',
            field=models.SmallIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='coupon',
            name='value',
            field=models.IntegerField(default=30),
        ),
    ]
