# Generated by Django 2.1.3 on 2018-11-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20181125_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
