# Generated by Django 2.1.3 on 2018-11-25 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20181125_0411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelocation',
            name='visited',
        ),
    ]
