# Generated by Django 2.1.3 on 2018-11-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_location_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
    ]
