# Generated by Django 2.1.3 on 2018-11-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20181125_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelocation',
            name='status',
            field=models.CharField(choices=[('TO_VISIT', 'TO_VISIT'), ('VISITED_CORRECTLY', 'VISITED_CORRECTLY'), ('VISITED_INCORRECTLY', 'VISITED_INCORRECTLY')], default='TO_VISIT', max_length=50),
        ),
        migrations.AlterField(
            model_name='gamequestion',
            name='status',
            field=models.CharField(choices=[('TO_ANSWER', 'TO_ANSWER'), ('ANSWERED_CORRECTLY', 'ANSWERED_CORRECTLY'), ('ANSWERED_INCORRECTLY', 'ANSWERED_INCORRECTLY')], default='TO_ANSWER', max_length=30),
        ),
    ]
