version: '3.7'

services:
  db:
    image: mdillon/postgis
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: '${DB_NAME}'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    restart: unless-stopped
    
  api:
    build: .
    ports:
      - '${API_PORT}:8000'
    volumes:
      - api:/api
    environment:
      DB_PORT: '${DB_PORT}'
      DB_NAME: '${DB_NAME}'
      DB_USER: '${DB_USER}'
      DB_PASSWORD: '${DB_PASSWORD}'
    depends_on:
      - db
    restart: unless-stopped
    
volumes:
  api:
    driver_opts:
      type: none
      device: '${PWD}/..'
      o: bind
